import { Footer } from '@/components/Footer'; import { Search } from '@/components/Search'; import { MarketScanner } from '@/components/MarketScanner'; import { getCommonsSnapshot, CommonsDataError } from '@/lib/commons'; import { analyseMarket } from '@/lib/strategy';
const fmt=(n:number)=>`${n<0?'−':''}${Math.abs(n/1000).toFixed(1)}K`;
export default async function Result({params}:{params:Promise<{username:string}>}){
 const username=decodeURIComponent((await params).username).replace(/^@/,'');
 let analysis:ReturnType<typeof analyseMarket>=null, error=''; let snapshot;
 try { snapshot=await getCommonsSnapshot(); analysis=analyseMarket(snapshot,username); if(!analysis) error=`@${username} is not present in the current Commons snapshot.`; } catch(e) { error=e instanceof CommonsDataError?e.message:'The strategy engine could not load this snapshot.'; }
 if(!analysis||!snapshot) return <main className="result"><nav><a className="brand" href="/">COMMONS <b>GTO</b></a><Search compact/><span className="source-state off"><i/>DATA UNAVAILABLE</span></nav><section className="unavailable"><h1>COMMONS DATA<br/>UNAVAILABLE</h1><p>{error.includes('not present')?error:"We couldn’t fetch the latest leaderboard. Try again after the next Commons update."}</p><a href="/">TRY AGAIN</a></section><Footer/></main>;
 const a=analysis,d=a.decision, sourceTime=snapshot.upstreamUpdatedAt??snapshot.fetchedAt;
 return <main className="result"><nav><a className="brand" href="/">COMMONS <b>GTO</b></a><Search compact/><span className="source-state ok"><i/>SNAPSHOT · {new Date(sourceTime).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'UTC'})} UTC</span></nav>
 <section className="decision-surface"><div className="identity"><p className="eyebrow">@{a.user.username.toUpperCase()}</p><h1>@{a.user.username}</h1><div className="position-strip"><span>RANK <b>#{a.user.rank.toLocaleString()}</b></span><span>SCORE <b>{fmt(a.user.totalScore)}</b></span><span>TOP 1000 <b>{fmt(a.target)}</b></span><span>YOUR VOUCH <b>{fmt(a.ownPower)}</b></span><span>LEFT <b>{a.remaining}</b></span></div></div>
 <div className="best"><p className="eyebrow">BEST MOVE</p><span className="route-type">{d.type}</span><h2>{d.type==='HOLD'?'HOLD.':`VOUCH @${d.candidate?.username}`}</h2>{d.type==='HOLD'?<p>Your floor is <b>{fmt(a.reservationValue)}</b>.<br/>The best trade available right now only brings back {a.actionable[0]?fmt(a.actionable[0].power):'nothing'}.<br/><br/>KEEP YOUR VOUCH.</p>:<p>{d.candidate?.username} adds <b>{fmt(d.inbound)}</b> to you.<br/>You add {fmt(a.ownPower)} to {d.candidate?.username}.<br/><br/>{d.margin>=0&&d.candidate&&d.candidate.totalScore+a.ownPower>=a.target?'Both of you clear the current cutoff.':''}</p>}<div className="best-metrics"><span>AFTER VOUCH <b>~#{d.rank.toLocaleString()}</b></span><span>ABOVE CUTOFF <b>{fmt(d.margin)}</b></span><span>COST <b>{d.type==='HOLD'?0:1} VOUCH</b></span></div></div>
 <div className="cutoff-visual"><div className="cutoff-axis"><span>YOUR SCORE<br/><b>{fmt(a.user.totalScore)}</b></span><i style={{left:`${Math.min(96,Math.max(4,a.user.totalScore/a.target*72))}%`}}/><i className="projected" style={{left:`${Math.min(96,Math.max(4,(a.user.totalScore+d.inbound)/a.target*72))}%`}}/><strong>TARGET {fmt(a.target)}</strong></div></div></section>
 <section className="routes"><header><div><p className="eyebrow">OTHER OPTIONS</p></div><div className="reservation"><span>YOUR FLOOR</span><b>{fmt(a.reservationValue)}</b><span>Below this, you’re giving up a better trade.</span></div></header><div className="route-grid"><article className="active"><small>01 / {d.type}</small><h3>{d.type==='HOLD'?'HOLD':`@${d.candidate?.username}`}</h3><b>{d.type==='HOLD'?'0 USED':`+${fmt(d.inbound)}`}</b><p>{d.type==='HOLD'?`FLOOR ${fmt(a.reservationValue)}`:d.margin>=0?'YOU IN':'NOT ENOUGH'}</p></article><article><small>02 / MARKET</small><h3>{a.whoNeeds} need your vouch</h3><b>{a.reciprocal} CAN GET YOU IN</b></article><article><small>03 / FINAL CUTOFF</small><h3>NOT ENOUGH DATA YET</h3><b>CURRENT LINE {fmt(a.target)}</b></article></div></section>
 <MarketScanner items={a.candidates} ownPower={a.ownPower} ourNeed={a.need}/>
 {a.user.totalScore>a.target&&<section className="defense"><p className="eyebrow">DEFENSIVE ANALYSIS</p><h2>Safety margin <b>+{fmt(a.user.totalScore-a.target)}</b></h2><p>A slash from an account with approximately {fmt((a.user.totalScore-a.target)/.35)}+ base could erase this margin.</p></section>}
 <section className="patron"><p className="eyebrow">BUILT BY @CYPHRGM</p><h2>Got a spare vouch?</h2><a href="https://x.com/intent/post?text=Hey%20%40commonsmade%2C%20I%20vouch%20for%20%40Cyphrgm" target="_blank">VOUCH @CYPHRGM ↗</a></section><Footer/></main>;
}
