import { Footer } from '@/components/Footer'; import { Search } from '@/components/Search'; import { MarketScanner } from '@/components/MarketScanner'; import { getCommonsSnapshot, CommonsDataError } from '@/lib/commons'; import { analyseMarket } from '@/lib/strategy';
const fmt=(n:number)=>`${n<0?'−':''}${Math.abs(n/1000).toFixed(1)}K`;
export default async function Result({params}:{params:Promise<{username:string}>}){
 const username=decodeURIComponent((await params).username).replace(/^@/,'');
 let analysis:ReturnType<typeof analyseMarket>=null, error=''; let snapshot;
 try { snapshot=await getCommonsSnapshot(); analysis=analyseMarket(snapshot,username); if(!analysis) error=`@${username} is not present in the current Commons snapshot.`; } catch(e) { error=e instanceof CommonsDataError?e.message:'The strategy engine could not load this snapshot.'; }
 if(!analysis||!snapshot) return <main className="result"><nav><a className="brand" href="/">COMMONS <b>GTO</b></a><Search compact/><span className="source-state off"><i/>DATA UNAVAILABLE</span></nav><section className="unavailable"><p className="eyebrow">ANALYSIS PAUSED</p><h1>No invented<br/>answers.</h1><p>{error} We never replace missing Commons records with sample users, scores, ranks, or counterparties.</p><a href="/">← TRY ANOTHER USER</a></section><Footer/></main>;
 const a=analysis,d=a.decision, sourceTime=snapshot.upstreamUpdatedAt??snapshot.fetchedAt;
 return <main className="result"><nav><a className="brand" href="/">COMMONS <b>GTO</b></a><Search compact/><span className="source-state ok"><i/>SNAPSHOT · {new Date(sourceTime).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'UTC'})} UTC</span></nav>
 <section className="decision-surface"><div className="identity"><p className="eyebrow">POSITION / @{a.user.username.toUpperCase()}</p><h1>@{a.user.username}</h1><div className="position-strip"><span>RANK <b>#{a.user.rank.toLocaleString()}</b></span><span>SCORE <b>{fmt(a.user.totalScore)}</b></span><span>TARGET <b>{fmt(a.target)}</b></span><span>VOUCH POWER <b>+{fmt(a.ownPower)}</b></span><span>REMAINING <b>{a.remaining}</b></span></div></div>
 <div className="best"><p className="eyebrow">YOUR BEST MOVE</p><span className="route-type">{d.type}</span><h2>{d.title}</h2>{d.type==='HOLD'?<p>Current reciprocal routes do not clear your reservation value with enough mutual incentive. Reassess after the next Commons snapshot.</p>:<p>You receive <b>+{fmt(d.inbound)}</b>. This is the highest-fit non-dominated direct route in the current market.</p>}<div className="best-metrics"><span>PROJECTED RANK <b>#{d.rank.toLocaleString()}</b></span><span>SAFETY MARGIN <b>{fmt(d.margin)}</b></span><span>VOUCHES USED <b>{d.type==='HOLD'?0:1}</b></span></div></div>
 <div className="cutoff-visual"><div className="cutoff-axis"><span>YOUR SCORE<br/><b>{fmt(a.user.totalScore)}</b></span><i style={{left:`${Math.min(96,Math.max(4,a.user.totalScore/a.target*72))}%`}}/><i className="projected" style={{left:`${Math.min(96,Math.max(4,(a.user.totalScore+d.inbound)/a.target*72))}%`}}/><strong>TARGET {fmt(a.target)}</strong></div></div></section>
 <section className="routes"><header><div><p className="eyebrow">OPTIMAL ROUTES</p><h2>Three decisions, ranked.</h2></div><div className="reservation"><span>VOUCH RESERVATION VALUE</span><b>~{fmt(a.reservationValue)}</b></div></header><div className="route-grid"><article className="active"><small>01 / {d.type}</small><h3>{d.title}</h3><b>{d.type==='HOLD'?'0 USED':`+${fmt(d.inbound)} INBOUND`}</b><p>{d.type==='HOLD'?'Keeps every remaining option open.':'Best balanced mutual utility for one scarce vouch.'}</p></article><article><small>02 / MARKET</small><h3>{a.whoNeeds} people need your size</h3><b>{a.reciprocal} CAN QUALIFY YOU BACK</b><p>Only efficient routes appear by default.</p></article><article><small>03 / PROJECTION</small><h3>Not enough history</h3><b>NO PROJECTED CUTOFF</b><p>We will not project until sufficient real snapshots exist.</p></article></div></section>
 <MarketScanner items={a.candidates} ownPower={a.ownPower} ourNeed={a.need}/>
 {a.user.totalScore>a.target&&<section className="defense"><p className="eyebrow">DEFENSIVE ANALYSIS</p><h2>Safety margin <b>+{fmt(a.user.totalScore-a.target)}</b></h2><p>A slash from an account with approximately {fmt((a.user.totalScore-a.target)/.35)}+ base could erase this margin.</p></section>}
 <section className="patron"><p className="eyebrow">USEFUL?</p><h2>If this changed your strategy,<br/>support the person who built it.</h2><a href="https://x.com/intent/post?text=Hey%20%40commonsmade%2C%20I%20vouch%20for%20%40Cyphrgm" target="_blank">VOUCH @CYPHRGM ↗</a></section><Footer/></main>;
}
