import { Footer } from '@/components/Footer'; import { Search } from '@/components/Search'; import { MarketScanner } from '@/components/MarketScanner'; import { getCommonsSnapshot, CommonsDataError } from '@/lib/commons'; import { analyseMarket } from '@/lib/strategy';
const fmt=(n:number)=>`${n<0?'−':''}${Math.abs(n/1000).toFixed(1)}K`;
export default async function Result({params}:{params:Promise<{username:string}>}){
 const username=decodeURIComponent((await params).username).replace(/^@/,'');
 let analysis:ReturnType<typeof analyseMarket>=null, error=''; let snapshot;
 try { snapshot=await getCommonsSnapshot(username); analysis=analyseMarket(snapshot,username); if(!analysis) error=`@${username} is not present in the current Commons snapshot.`; } catch(e) { error=e instanceof CommonsDataError?e.message:'The Commons snapshot could not be loaded.'; }
 if(!analysis||!snapshot) return <main className="result"><nav><a className="brand" href="/">COMMONS <b>GTO</b></a><Search compact/><span className="source-state off"><i/>DATA UNAVAILABLE</span></nav><section className="unavailable"><h1>COMMONS DATA<br/>UNAVAILABLE</h1><p>{error.includes('not present')?error:"We couldn’t fetch the latest leaderboard. Try again shortly."}</p><a href="/">TRY AGAIN</a></section><Footer/></main>;
 const a=analysis,d=a.decision, sourceTime=snapshot.upstreamUpdatedAt??snapshot.fetchedAt;
 const vouchLimit=snapshot.vouchLimit??7, slashLimit=snapshot.slashLimit??7;
 const vouchesLeft=a.user.vouchesRemaining ?? (a.user.vouchersUsed===undefined ? undefined : Math.max(0,vouchLimit-a.user.vouchersUsed));
 const slashesLeft=a.user.slashesRemaining ?? (a.user.slashesUsed===undefined ? undefined : Math.max(0,slashLimit-a.user.slashesUsed));
 return <main className="result"><nav><a className="brand" href="/">COMMONS <b>GTO</b></a><Search compact/><span className="source-state ok"><i/>UPDATED · {new Date(sourceTime).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',timeZone:'UTC'})} UTC</span></nav>
 <section className="decision-surface"><div className="identity"><p className="eyebrow">@{a.user.username.toUpperCase()}</p><h1>@{a.user.username}</h1><div className="position-strip"><span>RANK <b>#{a.user.rank.toLocaleString()}</b></span><span>TOTAL <b>{fmt(a.user.totalScore)}</b></span><span>BASE <b>{fmt(a.user.baseScore)}</b></span><span>TOP 1000 <b>{fmt(a.target)}</b></span><span>VOUCH <b>{fmt(a.ownPower)}</b></span><span>VOUCHES <b>{vouchesLeft===undefined?`${vouchLimit} TOTAL`:`${vouchesLeft} / ${vouchLimit}`}</b></span><span>SLASHES <b>{slashesLeft===undefined?`${slashLimit} TOTAL`:`${slashesLeft} / ${slashLimit}`}</b></span></div></div>
 <div className="best"><p className="eyebrow">BEST MOVE</p><span className="route-type">{d.type}</span><h2>{d.type==='HOLD'?'HOLD.':`VOUCH @${d.candidate?.username}`}</h2>{d.type==='HOLD'?<p>Your floor is <b>{fmt(a.reservationValue)}</b>.<br/>The best trade available right now only brings back {a.actionable[0]?fmt(a.actionable[0].power):'nothing'}.<br/><br/>KEEP YOUR VOUCH.</p>:<p>{d.candidate?.username} adds <b>{fmt(d.inbound)}</b> to you.<br/>You add {fmt(a.ownPower)} to {d.candidate?.username}.<br/><br/>{d.margin>=0&&d.candidate&&d.candidate.totalScore+a.ownPower>=a.target?'Both of you clear the current cutoff.':''}</p>}<div className="best-metrics"><span>AFTER VOUCH <b>~#{d.rank.toLocaleString()}</b></span><span>ABOVE CUTOFF <b>{fmt(d.margin)}</b></span><span>COST <b>{d.type==='HOLD'?0:1} VOUCH</b></span></div></div>
 <div className="cutoff-visual"><div className="cutoff-axis"><span>YOUR SCORE<br/><b>{fmt(a.user.totalScore)}</b></span><i style={{left:`${Math.min(96,Math.max(4,a.user.totalScore/a.target*72))}%`}}/><i className="projected" style={{left:`${Math.min(96,Math.max(4,(a.user.totalScore+d.inbound)/a.target*72))}%`}}/><strong>TOP 1000 {fmt(a.target)}</strong></div></div></section>
 <section className="routes"><header><div><p className="eyebrow">OTHER OPTIONS</p></div><div className="reservation"><span>YOUR FLOOR</span><b>{fmt(a.reservationValue)}</b><span>Below this, a better trade is available.</span></div></header><div className="route-grid"><article className="active"><small>01 / {d.type}</small><h3>{d.type==='HOLD'?'HOLD':`@${d.candidate?.username}`}</h3><b>{d.type==='HOLD'?'0 USED':`+${fmt(d.inbound)}`}</b><p>{d.type==='HOLD'?`FLOOR ${fmt(a.reservationValue)}`:d.margin>=0?'YOU IN':'NOT ENOUGH'}</p></article><article><small>02 / MARKET</small><h3>{a.whoNeeds} need your vouch</h3><b>{a.reciprocal} CAN GET YOU IN</b></article><article><small>03 / SUPPLY</small><h3>{vouchLimit} VOUCHES · {slashLimit} SLASHES</h3><b>{snapshot.nextVouchLimit&&snapshot.nextSupplyAt?`NEXT: ${snapshot.nextVouchLimit} ON ${new Date(snapshot.nextSupplyAt).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'UTC'})} UTC`:'CURRENT SUPPLY'}</b></article></div></section>
 <MarketScanner items={a.candidates} ownPower={a.ownPower} ourNeed={a.need}/>
 {a.user.totalScore>a.target&&<section className="defense"><p className="eyebrow">YOUR BUFFER</p><h2>+{fmt(a.user.totalScore-a.target)}</h2><p>A slash from an account with roughly {fmt((a.user.totalScore-a.target)/.35)}+ base would remove that margin.</p></section>}
 <section className="patron"><p className="eyebrow">BUILT BY @CYPHRGM</p><h2>Got one left?</h2><a href="https://x.com/intent/post?text=Hey%20%40commonsmade%2C%20I%20vouch%20for%20%40Cyphrgm" target="_blank">VOUCH @CYPHRGM ↗</a></section><Footer/></main>;
}
